apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deploy
spec:
  maxReplicas: 2
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy