image: gitpod/workspace-full
tasks:
  - name: prepare k8s
    command: |
      .gitpod/prepare-k8s.sh $K8S_TYPE
  - name: kernel dev environment
    init: |
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt update -y
      sudo apt install qemu qemu-system-x86 linux-image-generic libguestfs-tools sshpass netcat -y
      .gitpod/prepare-rootfs.sh
    command: |
      .gitpod/qemu.sh $K8S_TYPE
