apiVersion: v1
kind: Pod
metadata:
  name: nginx-swarmtest
  labels:
    name: nginx-swarmtest
spec:
  containers:
  - name: n1
    image: nginx:1.17.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

  - name: a2
    image: ichte/swarmtest:node
    resources:
      limits:
        memory: "150Mi"
        cpu: "100m"

    ports:
      - containerPort: 8085
