
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "172.16.10.100"
    config.vm.hostname = "master.xtl"

    config.vm.provider :libvirt do |lv|
       lv.title = "master.xtl"
       lv.cpus = 2
       lv.memory = 2048
    end
    
    config.vm.provision "shell", path: "./../install-docker-kube.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      usermod -aG $(id -u -n) vagrant

cat >>/etc/hosts<<EOF
172.16.10.100 master.xtl
172.16.10.101 worker1.xtl
172.16.10.102 worker2.xtl
EOF

    SHELL
  end