apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: cert-volume
          secret:
            secretName: "secret-nginx"
      containers:
      - name: n1
        image: wawahuy/swarmtest:nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: "/certs/"
            name: cert-volume
---
apiVersion: v1
kind: Service
metadata:
  name: svc4
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 31080

  - port: 8443
    targetPort: 443
    protocol: TCP
    name: https
    nodePort: 31443
    


